### PR TITLE
feat: new landing page icons

### LINKED ISSUE #157: Docs Landing Page Icons
## Skills
Some of the skills you could see yourself learning & applying as you go along:

- HTML, CSS (& Bootstrap),
- Git/GitHub
- Graphics

## What needs to be done

- Design custom icons for our [landing page](https://docs.atsign.com/)

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

### PR DESCRIPTION
**Pull request by PriyanshuRj**
**- What I did**
closes #157 
Added the newly created logs by @Nandini-13 to the home pages.

**- How I did it**
changed card/feature-icon to card/feature-image and added image links for the new logos
image

**- Description for the changelog**
Updated the logos on the home page

### CODE REVIEW

**Review by TylerTrott — DISMISSED** [review]
Great work! These icons are so cool! Thank you for your hard work!

**Comment by JeremyTubongbanua** [comment]
Hey @PriyanshuRj great work ! :)

Could you please post a picture of this in light mode?

**Comment by PriyanshuRj** [comment]
> Hey @PriyanshuRj great work ! :)
> 
> Could you please post a picture of this in light mode?

Ig they were not designed for light mode 
image
No problem I will change these logos then

**Comment by PriyanshuRj** [comment]
Actually I can't figure out a way to dynamically change the color of png and SVG logo. So can we introduce multi-color logos as they won't need color swap

**Comment by JeremyTubongbanua** [comment]
> Actually I can't figure out a way to dynamically change the color of png and SVG logo. So can we introduce multi-color logos as they won't need color swap

Look in the footer partial (under `layouts/`) the footer images show you how to go between light/dark ( I believe it's just a class )

**Comment by PriyanshuRj** [comment]
@JeremyTubongbanua please review these logos

**Review by JeremyTubongbanua — APPROVED** [review]
These are much better @PriyanshuRj :) thanks for your work

Also please post a screenshot of the new landing page icons in dark mode and light mode.

Here's an example of dark-mode/light-mode code: https://github.com/atsign-foundation/docs.atsign.com/blob/2b68145b9c8873d378565b35941b9dbe26fbc3b5/layouts/partials/main/footer.html#L3

I found just putting the images side-by-side with the classes `toggle-light` and `toggle-dark` works..
```html
<img class="toggle-light" src="{{ .RelPermalink }}" width="124em">
<img class="toggle-dark" src="{{ .RelPermalink }}" width="124em">
```

But if you're approach works, then that's fine +1

**Comment by JeremyTubongbanua** [comment]
Waiting for 2nd approval

**Review by xavierchanth — APPROVED** [review]

**Pull request merged**
