### PR TITLE
Renamed "Glossary" to "Reference", added glossary outline, and added dev blogs

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
**- What I did**
1. 85054aa45a3ef4b0183c33b312c6ffb7b68c4d14 Made an outline of all the terms in the google doc for the glossary
2. d85d00bc5643e3fa616f224653d435fa82418238 Renamed the "glossary" tab to "reference" so that I could add Developer Blogs there too! (I think developer blogs were a great resource for understanding the @platform)
3. 141b95b881b905975f1d16a7d1275bfb533c1256 Added all of the relevant developer blogs from medium.com that help with understanding the @platform (in my opinion)

**- How I did it**
For 3., I used html and embedded css styles if that's okay! If there's a better way to do lists, please lmk.

### CODE REVIEW

**Comment by xavierchanth** [comment]
Hey @JeremyTubongbanua, I like your thinking... I had actually thought about renaming to reference!

I intended to put developer blogs on a separate section of the site, ideally each page in this section should only cover a single topic/term. The content on these pages should be short, quick, and easy to read in order to quickly grasp the topic in question.

Please keep a list of the blog posts handy, we will definitely include them in the site, just not here.

Please make new pages for each topic/term, you can find the template for these files under archetype/docs-single.md.

Also, avoid using html in the md files, hugo has something called shortcodes which serve more advanced content needs.
We can make more as we find the need for more widgets, but you can find the currently available ones [here](https://dev3.atsign.wtf/docs/contribute/shortcodes).

**Review by xavierchanth — CHANGES_REQUESTED** [review]
See my comment for requested changes

**Review by Jesseadriano10 — COMMENTED** [review]
Based on Xavier's feedback I looked up how to work with Hugo and was able to set up the repo for  development on my machine. I will create a new pull request with my changes for approval/modification!

**Comment by JeremyTubongbanua** [comment]
Thanks for your input, @XavierChanth . I'll try and avert from html & css

See 00aea3cb1c48c3691c6df554661ddf9f4dac2203 for the individual terms

I also deleted the dev blogs- 0ce94a77523e4baed77432e4eacc7c4f2beb716c

A copy of the developer blogs can be found on a separate branch on my fork [here](https://raw.githubusercontent.com/JeremyTubongbanua/atsign.dev-3.0/developer_blogs/content/docs/reference/developer_blogs.md).

**Comment by JeremyTubongbanua** [comment]
> Thanks for your input, @XavierChanth . I'll try and avert from html & css
> 
> See [00aea3c](https://github.com/atsign-foundation/atsign.dev-3.0/commit/00aea3cb1c48c3691c6df554661ddf9f4dac2203) for the individual terms
> 
> I also deleted the dev blogs- [0ce94a7](https://github.com/atsign-foundation/atsign.dev-3.0/commit/0ce94a77523e4baed77432e4eacc7c4f2beb716c)
> 
> A copy of the developer blogs can be found on a separate branch on my fork [here](https://raw.githubusercontent.com/JeremyTubongbanua/atsign.dev-3.0/developer_blogs/content/docs/reference/developer_blogs.md).

Image of changes
Image of changes

**Comment by JeremyTubongbanua** [comment]
I will move all of these changes to a separate pull request with @Jesseadriano10 's changes in #39

**Pull request closed without merging**
