### PR TITLE
fix: Redirecting Issue in the Flutter documentation

### PR DESCRIPTION
**Pull request by PriyanshuRj**
**- What I did**
I updated the Links in the Flutter Get Started Section in the documentation at - https://docs.atsign.com/start/flutter/ .
They were earlier redirecting on the same page but now they open up on a new page.
**- How I did it**
I changed the links from the traditional MarkDown links to HTML anchor Tags to use the target attribute of the anchor tag to redirect to the new page.

**- How to verify it**
Open the Flutter portion of the Get Started section and click any of the available links to verify that they open on a new page.
image
The yellow text in the above image are all links. 

**- Description for the changelog**
This PR includes the rectified functionality of the Links present on the flutter portion of the Get Started section. They were earlier redirection on the same page after these changes they will redirect to a new page.

### CODE REVIEW

**Comment by PriyanshuRj** [comment]
Can i get a review on this PR please

**Review by JeremyTubongbanua — CHANGES_REQUESTED** [review]
hey @PriyanshuRj ! Great work!

One small problem is we don't like using html in our markdown files (because GoHugo does some stuff in the background with styling).

In case you ever **have** to use HTML please use our shortcodes. Shortcodes are basically React components. 

So in this case, instead of using the regular html a anchor tag, use the shortcode like this:

```
{{< a target="_blank" href="https://atsign.com/" >}} atsign.com {{< /a >}}
```

The tutorial for this can be found in our [Shortcodes guide](https://docs.atsign.com/contribute/shortcodes/links/)

**Comment by PriyanshuRj** [comment]
Okey @JeremyTubongbanua got your point will modify it.

**Comment by PriyanshuRj** [comment]
Updated the conventional anchor tags to shortcode tags.

**Review by xavierchanth — DISMISSED** [review]

**Review by xavierchanth — DISMISSED** [review]
Looks good!

**Review by JeremyTubongbanua — CHANGES_REQUESTED** [review]
Hey @PriyanshuRj thanks for your PR

One small change and I think it's good to go

Please use the shortcode like this

```
{{< a href="https://code.visualstudio.com/" target="_blank">}}Visual Studio Code{{< /a >}}
```

as opposed to this
```
{{<a href="https://code.visualstudio.com/" target="_blank">}}Visual Studio Code{{</a>}}
```

Just to stay consistent with the rest of our documentation. Thank you!

**Review by JeremyTubongbanua — APPROVED** [review]
Great work

**Review by xavierchanth — APPROVED** [review]

**Pull request merged**
