### PR TITLE
feat: Added new icons

### PR DESCRIPTION
**Pull request by Nandini-13**
I made new logos for the landing page using graphics. I got confused with the code, so I haven't implemented them into the website yet, just inserted the logos in the static folder.

### CODE REVIEW

**Comment by TylerTrott** [comment]
These are pretty cool! I have added some more team members to review them

**Review by xavierchanth — COMMENTED** [review]
Cool icons! Can I request that you move them under `/assets/img/icons` and rename the files to be more descriptive?

**Comment by Nandini-13** [comment]
Sure, will do that.

**Comment by Nandini-13** [comment]
I have relocated and renamed them, is it okay right now?

resolved #157

**Review by TylerTrott — APPROVED** [review]
LGTM!

**Comment by xavierchanth** [comment]
Nice work @Nandini-13 !

**Comment by Nandini-13** [comment]
Thank you😊

**Pull request merged**
