### PR TITLE
Fixed SEO descriptions in content/docs/sdk/

### PR DESCRIPTION
**Pull request by AyushK-101**
**- What I did**
Fixed SEO descriptions

**- How I did it**
Updated relevant .md files
**- How to verify it**

**- Description for the changelog**

Updated SEO descriptions in content/docs/sdk/ regarding issue #186

### CODE REVIEW

**Review by TylerTrott — APPROVED** [review]
Good stuff!

**Comment by JeremyTubongbanua** [comment]
@AyushK-101 
Thank you for contributing to us in Hacktoberfest 2022!

Your PR was accepted, merged, and it closed an issue. You could be eligible for a prize. 

To be eligible, please send an email to [hacktoberfest@atsign.com](mailto:hacktoberfest@atsign.com) with a screenshot of the PR approval email. (Or you can forward the PR approval email to us). This is to prove that your email corresponds to the correct GitHub account. We will contact you through that email with details of your prize (if you are eligible). 

Be sure to look out for us on our socials. We love community!
YouTube: https://www.youtube.com/c/AtsignCo
Twitter: https://twitter.com/atsigncompany
LinkedIn: https://www.linkedin.com/company/atsigncompany/

Discord: http://discord.atsign.com/
GitHub: https://github.com/atsign-foundation 

Thank you again! 
~Jeremy, SWE at Atsign

**Comment by JeremyTubongbanua** [comment]
Exception: #186 was a multi-assigned issue and is still awaiting on other developer PRs. Please attach this detail when you send us an email.

**Comment by JeremyTubongbanua** [comment]
Hey @AyushK-101 if you're interested in winning a prize, please email us [mailto:hacktoberfest@atsign.com](hacktoberfest@atsign.com)

**Pull request merged**
