### PR TITLE
feat: Changes for What is AtSign

### LINKED ISSUE #159: Docs What is Atsign?
## Skills
Some of the skills you could see yourself learning & applying as you go along:

- HTML, CSS (& Bootstrap)
- Git/GitHub
- GoHugo
- English

## What needs to be done
On our current landing page is intimidating because we go straight into code without ever explaining what Atsign is.
A button on the landing page with text similar to “What is Atsign?” that takes them to another page explaining Atsign would be a great addition to the landing page.

## How to do it
- Create a shortcode button in `layouts/shortcodes/button/`. See the `link.html` shortcode as an example. Shortcodes are just like Flutter widgets (or React components): they are reusable pieces of UI.
- To use the shortcode, head over to the [shortcodes guide](https://docs.atsign.com/contribute/shortcodes/button/) and there you will see an example of the shortcode being used and also how to use it yourself. For example, to use the `button/link` shortcode, you simply just type `{{< button/link href="#" type="secondary" text="Secondary" >}}` into any markdown file under `content/`.
- Once you’ve created your shortcode, you can use it in the landing page in `content/docs/_index.md`.
- (Optional) Create a page explaining what (you think) Atsign is and what we do here. Do your best! Then make your shortcode button take you to this new markdown page you’ve created.

## Support
In case you need any kind of help (such as getting your environment setup or asking questions about our tech) don’t be afraid to ask in our [discord](https://discord.atsign.com). There is a team full of developers ready to jump in and help on whatever your issue may be.

### PR DESCRIPTION
**Pull request by Ruchika30**
**- What I did**
I have added changes for users to know "What is AtSign"
**- How I did it**
I have added a button which will take them to https://atsign.com/

**- How to verify it**
Running the server will reflect  these changes and navigating to the landing page shows the button "What is AtSign"

**- Description for the changelog**
Made the shortcode button component, about-atSign.html and linked it to be used in _index.md in content/docs/

closes #159

### CODE REVIEW

**Comment by Ruchika30** [comment]
Somehow I am not able to add the info icon. I tried various classes from font-awesome version 4. But still unable to do so. 
Kindly help me in understanding what am I missing  @JeremyTubongbanua . I will update the changes for the same

**Comment by JeremyTubongbanua** [comment]
No worries @Ruchika30, thank you for your work.
Could you give a screenshot of the button please?

**Comment by Ruchika30** [comment]
> No worries @Ruchika30, thank you for your work. Could you give a screenshot of the button please?

Screenshot 2022-10-08 at 9 05 33 PM

**Review by JeremyTubongbanua — CHANGES_REQUESTED** [review]
Thank you @Ruchika30 

Please change the text to "Atsign" (the company name is not "AtSign"). And please paste a screenshot of what it looks like in dark mode too :)

Otherwise, it LGTM

**Comment by Ruchika30** [comment]
> Thank you @Ruchika30
> 
> Please change the text to "Atsign" (the company name is not "AtSign"). And please paste a screenshot of what it looks like in dark mode too :)
> 
> Otherwise, it LGTM

Updated the changes @JeremyTubongbanua . What do we do about the info icon ? Should I add the right arrow back again?

Screenshot 2022-10-11 at 11 46 21 PM
Screenshot 2022-10-11 at 11 46 16 PM

**Comment by JeremyTubongbanua** [comment]
> > Thank you @Ruchika30
> > Please change the text to "Atsign" (the company name is not "AtSign"). And please paste a screenshot of what it looks like in dark mode too :)
> > Otherwise, it LGTM
> 
> Updated the changes @JeremyTubongbanua . What do we do about the info icon ? Should I add the right arrow back again?
> 
> Screenshot 2022-10-11 at 11 46 21 PM
> 
> Screenshot 2022-10-11 at 11 46 16 PM

Hmm if you could make the info icon have a little "i" inside the circle, then that would be great.

**Comment by JeremyTubongbanua** [comment]
image

Something like this is what we are aiming for ^

Also making the text a little bit smaller and lighter would be great @Ruchika30

**Comment by TylerTrott** [comment]
Closing as #185 resolved this

**Pull request closed without merging**
