### PR TITLE
feat: mandatory/optional & default values for AtClientPreference in flutter sdk reference, closes #165

### LINKED ISSUE #165: AtClientPreference parameters state mandatory/optional
## What needs to be done

The attributes on https://docs.atsign.com/sdk/flutter/at_client_preference/ should state mandatory/optional,, feedback taken from @ralfeus on discord.

### PR DESCRIPTION
**Pull request by kaggrwal**
closes #165 

**- Description for the changelog**
Added mandatory/option and default values for preferences in flutter sdk

### CODE REVIEW

**Comment by kaggrwal** [comment]
@JeremyTubongbanua Please review it and merge it.

**Comment by JeremyTubongbanua** [comment]
`namespace` is optional @kaggrwal

**Review by JeremyTubongbanua — APPROVED** [review]
Please post a screenshot @kaggrwal for other reviewers.

I think this is good because it states which parameters have default values (and for the ones that don't have default values, should be provided by either the developer or by another piece of software like the onboarding widget)

**Comment by kaggrwal** [comment]
Adding the screenshot for the changes. 

image

**Review by gkc — APPROVED** [review]
LGTM

**Comment by JeremyTubongbanua** [comment]
@kaggrwal 
Thank you for contributing to us in Hacktoberfest 2022!

Your PR was accepted, merged, and it closed an issue. You could be eligible for a prize. 

To be eligible, please send an email to [hacktoberfest@atsign.com](mailto:hacktoberfest@atsign.com) with a screenshot of the PR approval email. (Or you can forward the PR approval email to us). This is to prove that your email corresponds to the correct GitHub account. We will contact you through that email with details of your prize (if you are eligible). 

Be sure to look out for us on our socials. We love community!
YouTube: https://www.youtube.com/c/AtsignCo
Twitter: https://twitter.com/atsigncompany
LinkedIn: https://www.linkedin.com/company/atsigncompany/

Discord: http://discord.atsign.com/
GitHub: https://github.com/atsign-foundation 

Thank you again! 
~Jeremy, SWE at Atsign

**Comment by JeremyTubongbanua** [comment]
Exception: #186 was a multi-assigned issue and is still awaiting on other developer PRs. Please attach this detail when you send us an email.

**Pull request merged**
