### PR TITLE
First term definition for the AtSign Glossary!

### PR DESCRIPTION
**Pull request by Jesseadriano10**
**- What I did**
-Set up repo and Hugo for development on my machine.
- Created a new single page for the privacy definition

**- How I did it**
I pulled the template from archetypes and added my definition draft from the google doc.
**- How to verify it**
Run the changes on a local server to make sure what I added is correct. Should look like this:

image

**- Description for the changelog**

### CODE REVIEW

**Review by TylerTrott — APPROVED** [review]
LGTM, I'd wait until you get one more approval before merging :) Thanks for the contribution!!!!

**Review by JeremyTubongbanua — DISMISSED** [review]
Edit `encryption.md` with `weight: 2` for ordering purposes

**Comment by Jesseadriano10** [comment]
> Edit `encryption.md` with `weight: 2` for ordering purposes
Do we want alphabetical order? If I leave all weights as 1 then the items will automatically order themselves. However, I do not know if this will be an issue.

**Comment by JeremyTubongbanua** [comment]
> Edit `encryption.md` with `weight: 2` for ordering purposes
>  > Do we want alphabetical order? If I leave all weights as 1 then the items will automatically order themselves. However, I do not know if this will be an issue.

Yeah, I guess glossaries are in alphabetical order.
IMO, it will feel out of place having something like PKAM and CRAM on opposite sides of the glossary though.

Probably a problem to worry about later. Thanks Jesse!

**Review by JeremyTubongbanua — APPROVED** [review]

**Pull request merged**
