### PR TITLE
feat: Flutter Vikings tweaks

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
# Tasks
listed by @anthonyvprakash :

- [x] 1. change atPlatform image branding at the top left
- [x] 2. take out IoT tab from the nav bar
- [x] 3. `/docs/` "atPlatform Documentation" ==> "Welcome to the atPlatform Documentation"
- [ ] 4. better looking cards in `/docs/` (hover effect & icons?) (like in https://docs.shoreline.io/)
- [x] 5. change `@` to `at`
- [ ] 6. side bar titles lowercase
- [x] 7. route `./` path to go to `/docs/` path *temporary solution implemented, see comments below
- [x] 8. footer similar to https://atsign.com

Other tasks I took on myself:

- [x] changed sidebar titles to be shorter
- [x] added toc to every reference page
- [x] clicking the atPlatform logo will take you to `/docs/`

# Proof

2. Took out IoT
Screen Shot 2022-08-23 at 9 20 30 PM

3. "Welcome to the atPlatform Documentation"
Screen Shot 2022-08-23 at 9 20 54 PM

5 
Screen Shot 2022-08-23 at 9 21 17 PM
Screen Shot 2022-08-23 at 9 21 29 PM

8.
Screen Shot 2022-08-23 at 9 21 44 PM

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
@XavierChanth @anthonyvprakash 
Turns out 1. is not easy because it is text and not an image. It is not a simple image swap
For 7., I am thinking of just making the `/docs/` page into a shortcode and just reuse it in both `./` and `/docs/`. This won't be a sustainable solution though. But it will work fine for Flutter Vikings

**Review by anthonyvprakash — DISMISSED** [review]

**Comment by JeremyTubongbanua** [comment]
> I was able to do 1. by going to `node_modules/@hyas/doks/layouts/partials/header/header.html` and changing line 14 to ``.. but this won't work because it's in `node_modules/` 😂 .
> 
> Screen Shot 2022-08-23 at 9 58 49 PM
> 
> How do you even change the title @XavierChanth ? I can't find the nav anywhere in the `layouts/`. I tried changing the `"name"` in the web manifest inside `static/` but it did not change for me.
> 

Ignore. I figured out 1. [33149ba](https://github.com/atsign-foundation/atsign.dev-3.0/pull/101/commits/33149bacd960b3d2782c04461ce8ed4410a572a5)

**Comment by JeremyTubongbanua** [comment]
Screen Shot 2022-08-24 at 12 01 11 PM
Not part of the requested changes, but I shortened the sidebar titles because on some pages, it would crunch the titles in attempt to fit the table of contents on the right side.
https://github.com/atsign-foundation/atsign.dev-3.0/pull/101/commits/7eab06cb554e6b6ce566791f0881cafd87e0ab8a

**Comment by JeremyTubongbanua** [comment]
Enabled table of contents for all reference pages to remain consistent with the other pages
https://github.com/atsign-foundation/atsign.dev-3.0/pull/101/commits/273b8407bce80c6b19055a5e5823700ab66a213e

**Comment by JeremyTubongbanua** [comment]
Temporary landing page `./`
Screen Shot 2022-08-24 at 12 53 31 PM
https://github.com/atsign-foundation/atsign.dev-3.0/pull/101/commits/9ebaa7ce9c07d0010d1437770a7b1c4ab8a01468

**Review by anthonyvprakash — APPROVED** [review]

**Pull request merged**
