### PR TITLE
fix: unlinked text-email

### LINKED ISSUE #184: Unlinked Text on the Flutter Onboarding page
**Describe the bug**
There is no email id linked to `email us at` on the [flutter onboarding](https://docs.atsign.com/sdk/flutter/onboarding/) page.

**To Reproduce**
- Add the correct hyperlink of the `mailto:`
- Make the changes in https://github.com/atsign-foundation/docs.atsign.com/blob/trunk/content/docs/sdk/flutter/onboarding.md

**Expected behavior**
Should redirect to the default mailing app of the user.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by srini047**
⚒️Fixes #184 

**- What I did**
Added the email: [support@atsign.com](mailto:support@atsign.com) on the onboarding page of flutter.

**- How I did it**
Added a `mailto:` hyperlink at the appropriate position

**- Description for the changelog**

Fixed the unlinked text by redirecting to the default mailing app of the user.

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
Thanks for making a draft PR @srini047 :)

**Comment by srini047** [comment]
> Thanks for making a draft PR @srini047 :)

Pleasure is mine😁

**Comment by srini047** [comment]
Also looking forward to further steps to successfully fix the issue.

**Comment by JeremyTubongbanua** [comment]
> Also looking forward to further steps to successfully fix the issue.

Try this

```
[support@atsign.com](mailto://support@atsign.com)
```

^ That is how you put links in markdown.

Alternatively, you can use our anchor [shortcode](https://docs.atsign.com/contribute/shortcodes/links/)

```
{{< a rel="canonical" target="_blank" href="https://atsign.com/" >}} atsign.com {{< /a >}}
```

**Comment by srini047** [comment]
> 

Used the first approach (the second one didn't produce desired output).

**Review by TylerTrott — APPROVED** [review]
LGTM! Thank you for your contribution!

**Comment by JeremyTubongbanua** [comment]
@srini047 
Hey! Thank you for your contribution. Your PR was accepted, merged, and it closed an issue. You could be eligible for a prize. 

To be eligible, please send an email to [hacktoberfest@atsign.com](mailto:hacktoberfest@atsign.com) with a screenshot of the PR approval email (or just forward the PR approval email to us). This is to prove that your email corresponds to the correct GitHub account. Thank you!

When it comes time to distribute the prizes, we will look at all the emails we've received from that email so don't forget to do this!

**Pull request merged**
