### PR TITLE
Move `reference/` above `contribute/`

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
**- What I did**
1. Moved `REFERENCE` above `CONTRIBUTE TO THIS SITE` using weights (see Fig A)
2. Extracted SDK services (see Fig B) (I personally think this is better and easier for the user to quickly find information on the packages. Also makes it clear that there are some core packages). (This is a rough draft for now, just considering general layout)

**- How to verify it**
Fig A - weights of each dir's `_index.md`
```
// BEFORE
start/ "Getting Started" - 99
tutorials/ "Samples and Tutorials" - 98
sdk/ "SDK Reference" - 97
atplatform/ - 96
contribute/ - 95
reference/ "Reference " - 94

//AFTER
start/ "Getting Started" - 99
tutorials/ "Samples and Tutorials" - 98
sdk/ "SDK Reference" - 97
atplatform/ - 96
reference/ "Reference " - 95
contribute/ - 94
```

Fig B - extracted code labs into singles
- also note that reference is above contribute
image

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
If there is an disagreement, we can close this pull request. This is just a proposal.

**Comment by xavierchanth** [comment]
> If there is an disagreement, we can close this pull request. This is just a proposal.

You can open an issue for proposals, it gives opportunity to discuss whether work is necessary or not before doing it.

The problem with expanding out the codelab is that once all of our various packages are added, the section will become extremely cluttered. I already dislike the 2 layered nestings, 3 will just make it worse.

I like the idea of renaming the codelab to `at_client_sdk`, but it should probably be `at_client` so that it matches the package name. at_commons won't need its own section, and it can be included in the at_client codelab, since the two are deeply coupled.

Reordering reference and contribute is fine.

**Comment by JeremyTubongbanua** [comment]
> > If there is an disagreement, we can close this pull request. This is just a proposal.
> 
> You can open an issue for proposals, it gives opportunity to discuss whether work is necessary or not before doing it.
> 
> The problem with expanding out the codelab is that once all of our various packages are added, the section will become extremely cluttered. I already dislike the 2 layered nestings, 3 will just make it worse.
> 
> I like the idea of renaming the codelab to `at_client_sdk`, but it should probably be `at_client` so that it matches the package name. at_commons won't need its own section, and it can be included in the at_client codelab, since the two are deeply coupled.
> 
> Reordering reference and contribute is fine.

Thank you for your input.

I agree that it will get clustered with all the nesting. I also agree that naming the codelab `at_client` is good.

**Comment by JeremyTubongbanua** [comment]
Commit f678fdf7bd22116b6815a5ef9d04ae1b3a1ea06b

image

`at_onboarding_flutter` codelab
image

`at_client` codelab
image

**Comment by JeremyTubongbanua** [comment]
@XavierChanth See reverted commits

Layout as of now:
image

**Review by xavierchanth — APPROVED** [review]

**Pull request merged**
