### PR TITLE
feat: platform statement images

### LINKED ISSUE #135: feat: new "platform image statements"
# "platform statements" graphics

image

We need 3 versions of "platform image statements" like the one above:

- [ ] "An open-source, full-stack platform for creating end-to-end encrypted Java apps"
- [ ] "An open-source, full-stack platform for creating end-to-end encrypted Dart/Flutter apps"
- [ ] "An open-source, full-stack platform for simplifying and securing IoT devices"

Then implement them in `/start/flutter`, `/start/java` and `/start/iot`

### PR DESCRIPTION
**Pull request by kaggrwal**
**- Description for the changelog**

closes #135

### CODE REVIEW

**Comment by kaggrwal** [comment]
Hi @JeremyTubongbanua, I have tried designing some images here related to #135 . I'm not an expert with graphic designing, but i tried out a little bit here. Please review them and let me know, if there are any improvements that are required. 

Hope you would like them :)

**Comment by JeremyTubongbanua** [comment]
@hakeemawbrey and @Dariamarg would you kindly give some feedback?

**Review by TylerTrott — CHANGES_REQUESTED** [review]
These are SO great! For the first one Flutter_Platform, we would like to replace  "Private mobile apps" with "Flutter Apps", just as you've done in Java_Platform where you say "Java Apps". May you also upload these as ".png" files please? Thank you ! One more thing, what Font are you using within these images?

**Review by JeremyTubongbanua — CHANGES_REQUESTED** [review]
The images are supposed to be platform "statements" (aka sentences). Can you please make the 3 images look a little more different? At glance, they are the same image but with different text and it would make the docs site a lot more lively if they were different.

Also sorry that this wasn't stated in the issue, but make sure you are using free fonts (so that we have the rights to use it), otherwise, Poppins/Inter are our official fonts. A darkmode and a lightmode version would be very nice.

That is my feedback, thanks so much for your work thus far @kaggrwal. Awesome work!

**Comment by kaggrwal** [comment]
> These are SO great! For the first one Flutter_Platform, we would like to replace "Private mobile apps" with "Flutter Apps", just as you've done in Java_Platform where you say "Java Apps". May you also upload these as ".png" files please? Thank you ! One more thing, what Font are you using within these images?

Thanks for the feedback @TylerTrott, i will replace "Private mobile apps" with "Flutter Apps", and regarding fonts, i will use 'Poppins' if that is being used in the project.

**Comment by kaggrwal** [comment]
> The images are supposed to be platform "statements" (aka sentences). Can you please make the 3 images look a little more different? At glance, they are the same image but with different text and it would make the docs site a lot more lively if they were different.
> 
> Also sorry that this wasn't stated in the issue, but make sure you are using free fonts (so that we have the rights to use it), otherwise, Poppins/Inter are our official fonts. A darkmode and a lightmode version would be very nice.
> 
> That is my feedback, thanks so much for your work thus far @kaggrwal. Awesome work!

Thanks for the feedback @JeremyTubongbanua .  Please clarify the below points

1. Should i make the images with statements as i tried with that but those weren't looking much creative and lively ?
2. So, Each platform should have a different image ?
3. I will use Poppins as the fonts, would that be fine ?
4. So, we need 6 images, 3 for light mode and 3 for dark mode ?

Again, thanks for providing me this opportunity. Glad to be part of atSign community :)

**Comment by JeremyTubongbanua** [comment]
> > The images are supposed to be platform "statements" (aka sentences). Can you please make the 3 images look a little more different? At glance, they are the same image but with different text and it would make the docs site a lot more lively if they were different.
> > Also sorry that this wasn't stated in the issue, but make sure you are using free fonts (so that we have the rights to use it), otherwise, Poppins/Inter are our official fonts. A darkmode and a lightmode version would be very nice.
> > That is my feedback, thanks so much for your work thus far @kaggrwal. Awesome work!
> 
> Thanks for the feedback @JeremyTubongbanua . Please clarify the below points
> 
> 1. Should i make the images with statements as i tried with that but those weren't looking much creative and lively ?
> 2. So, Each platform should have a different image ?
> 3. I will use Poppins as the fonts, would that be fine ?
> 4. So, we need 6 images, 3 for light mode and 3 for dark mode ?
> 
> Again, thanks for providing me this opportunity. Glad to be part of atSign community :)

1. Yes, we'd like for them to be statements so that it describes the atPlatform for a particular platform.
2. Yes, they should all also *look* different so that when the viewer goes through each page, they are met with a different vibe.
3. Poppins is fine
4. Yes

Thanks for accepting our feedback @kaggrwal

**Comment by kaggrwal** [comment]
> > > The images are supposed to be platform "statements" (aka sentences). Can you please make the 3 images look a little more different? At glance, they are the same image but with different text and it would make the docs site a lot more lively if they were different.
> > > Also sorry that this wasn't stated in the issue, but make sure you are using free fonts (so that we have the rights to use it), otherwise, Poppins/Inter are our official fonts. A darkmode and a lightmode version would be very nice.
> > > That is my feedback, thanks so much for your work thus far @kaggrwal. Awesome work!
> > 
> > 
> > Thanks for the feedback @JeremyTubongbanua . Please clarify the below points
> > 
> > 1. Should i make the images with statements as i tried with that but those weren't looking much creative and lively ?
> > 2. So, Each platform should have a different image ?
> > 3. I will use Poppins as the fonts, would that be fine ?
> > 4. So, we need 6 images, 3 for light mode and 3 for dark mode ?
> > 
> > Again, thanks for providing me this opportunity. Glad to be part of atSign community :)
> 
> 1. Yes, we'd like for them to be statements so that it describes the atPlatform for a particular platform.
> 2. Yes, they should all also _look_ different so that when the viewer goes through each page, they are met with a different vibe.
> 3. Poppins is fine
> 4. Yes
> 
> Thanks for accepting our feedback @kaggrwal

@JeremyTubongbanua / @TylerTrott  i have uploaded 2 images for java platform (Light and Dark), let me know it it looks good. If it is fine, i will proceed with other platform too.

**Comment by JeremyTubongbanua** [comment]
> > > > The images are supposed to be platform "statements" (aka sentences). Can you please make the 3 images look a little more different? At glance, they are the same image but with different text and it would make the docs site a lot more lively if they were different.
> > > > Also sorry that this wasn't stated in the issue, but make sure you are using free fonts (so that we have the rights to use it), otherwise, Poppins/Inter are our official fonts. A darkmode and a lightmode version would be very nice.
> > > > That is my feedback, thanks so much for your work thus far @kaggrwal. Awesome work!
> > > 
> > > 
> > > Thanks for the feedback @JeremyTubongbanua . Please clarify the below points
> > > 
> > > 1. Should i make the images with statements as i tried with that but those weren't looking much creative and lively ?
> > > 2. So, Each platform should have a different image ?
> > > 3. I will use Poppins as the fonts, would that be fine ?
> > > 4. So, we need 6 images, 3 for light mode and 3 for dark mode ?
> > > 
> > > Again, thanks for providing me this opportunity. Glad to be part of atSign community :)
> > 
> > 
> > 
> > 1. Yes, we'd like for them to be statements so that it describes the atPlatform for a particular platform.
> > 2. Yes, they should all also _look_ different so that when the viewer goes through each page, they are met with a different vibe.
> > 3. Poppins is fine
> > 4. Yes
> > 
> > Thanks for accepting our feedback @kaggrwal
> 
> @JeremyTubongbanua / @TylerTrott i have uploaded 2 images for java platform (Light and Dark), let me know it it looks good. If it is fine, i will proceed with other platform too.

Hey @kaggrwal this is definitely better, but I am still having trouble reading the actual statement. Sorry to make you go back again, but if you could find out how to make the statement more readable while also breaking down the key words like  the image below, that would be awesome 

image

Thanks so much again @kaggrwal :)

**Comment by kaggrwal** [comment]
@JeremyTubongbanua I have updated all images, please review and merge.

**Review by JeremyTubongbanua — CHANGES_REQUESTED** [review]
I like these, just 2 requests:

- [ ] For the IoT image, can you make it more obvious that this is for IoT? Just like how the Java image and the Flutter/Dart image have the Java & Flutter/Dart logos, could we somehow get a picture for IoT? I know there's a picture of a computer, but the computer blends in too much with the background and text and something like a colourful drone would be amazing.
- [ ] For the Java image, Surveillance's letter "e" wraps to the next line. Could you make "Surveillance" one word by decreasing the font or something?

**Comment by kaggrwal** [comment]
> I like these, just 2 requests:
> 
> * [ ]  For the IoT image, can you make it more obvious that this is for IoT? Just like how the Java image and the Flutter/Dart image have the Java & Flutter/Dart logos, could we somehow get a picture for IoT? I know there's a picture of a computer, but the computer blends in too much with the background and text and something like a colourful drone would be amazing.
> * [ ]  For the Java image, Surveillance's letter "e" wraps to the next line. Could you make "Surveillance" one word by decreasing the font or something?

@JeremyTubongbanua check now.

**Review by TylerTrott — APPROVED** [review]
Thank you so much for all of your hard work @kaggrwal. We really appreciate you going above and beyond :)

**Pull request merged**
