### PR TITLE
chore: Updated atPlatform brand name

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

find and replace all instances `@platform` and `Atsign platform` with `atPlatform`

**- How I did it**

**- How to verify it**

**- Description for the changelog**
chore: Updated atPlatform brand name

### CODE REVIEW

**Review by jenmonroe — DISMISSED** [review]
Looking good, @XavierChanth! 

One thing I found: The way that **AtSign** generates revenue is by using our special identifier which is known as an @sign. 

It looks like the updates to Atsign were already made, so wanted to catch this AtSign in case it slipped by.

**Comment by xavierchanth** [comment]
> Looking good, @XavierChanth!
> 
> One thing I found: The way that **AtSign** generates revenue is by using our special identifier which is known as an @sign.
> 
> It looks like the updates to Atsign were already made, so wanted to catch this AtSign in case it slipped by.

Good catch, I will double check all the "atsign" and "@‎sign" variants as well.

**Comment by xavierchanth** [comment]
Summary of added changes @jenmonroe:

"at [platform/protocol/sign]" -> "at[Platform/Protocol/Sign]"
"@[platform/protocol/sign]" -> "at[Platform/Protocol/Sign]"
"@ [platform/protocol/sign]" -> "at[Platform/Protocol/Sign]"
"@app" -> "atApp" (wasn't sure about this one)

Did a check for all "atsign" variations to ensure the correct casing is used in the correct places.

**Review by jenmonroe — APPROVED** [review]
All good - we can connect on the other edits separately. thanks!

**Pull request merged**
